# 통계표 노드 설계

###  0. 데이터 불러오기
- 통계청 조사 한정 통계표 목록

In [71]:
from IPython.display import display
import pandas as pd
import warnings
warnings.simplefilter(action='ignore', category=pd.errors.SettingWithCopyWarning)


path_table = "./raw_data/(참고1-2)승인통계_통계표.csv"

df_table = pd.read_csv(path_table, encoding='utf-8-sig')

In [72]:
df_table.columns

Index(['기관코드', '기관명', '승인번호', '통계명', '통계표ID', '통계표명', '수록기간(전체정보)', '주기',
       '시작연도', '마지막연도'],
      dtype='object')

In [73]:
df_table = df_table[["통계표ID", "통계표명", "승인번호", "기관코드", "주기", "시작연도", "마지막연도"]]

In [74]:
df_table

,통계표ID,통계표명,승인번호,기관코드,주기,시작연도,마지막연도
0,DT_1SA100,"세종특별자치시 농가, 농가인구",13002,101,부정기,2013,2013
1,DT_1SA101,경지규모별 농가수,13002,101,부정기,2013,2013
2,DT_1SA1011,논면적규모별 농가수,13002,101,부정기,2013,2013
3,DT_1SA1011_01,"농가수, 논면적",13002,101,부정기,2013,2013
4,DT_1SA1013,밭면적규모별 농가수,13002,101,부정기,2013,2013
...,...,...,...,...,...,...,...
11811,DT_1A02038,시도별 · 이동유형별 귀산촌인,930002,101,년,2018,2023
11812,DT_1A02039,시도별 · 성별 · 연령별 귀산촌가구주,930002,101,년,2018,2023
11813,DT_1A02040,시도별(시군별) · 가구원수별 귀산촌가구,930002,101,년,2018,2023
11814,DT_1A02041,시도별(시군별) · 가구 구성형태별 귀산촌가구,930002,101,년,2018,2023
11815,DT_1A02042,시도별 · 전입사유별 귀산촌가구,930002,101,년,2018,2023

In [75]:
df_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11816 entries, 0 to 11815
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   통계표ID   11816 non-null  object
 1   통계표명    11816 non-null  object
 2   승인번호    11816 non-null  int64
 3   기관코드    11816 non-null  int64
 4   주기      11816 non-null  object
 5   시작연도    11816 non-null  int64
 6   마지막연도   11816 non-null  int64
dtypes: int64(4), object(3)
memory usage: 646.3+ KB

주기 : 5년, 4년, 3년, 2년, 년, 분기, 반기, 월, 부정기

In [76]:
df_table["주기"].value_counts()

주기
5년           5343
년            3669
2년           1577
월             333
월,분기,년        219
분기,년          213
반기            136
분기            124
부정기            90
3년             54
월,년            29
월,분기           15
반기,년            7
4년              3
분기,반기,년         2
분기,반기           1
월,분기,반기,년       1
Name: count, dtype: int64

### 1. 통계표명 간소화
- llm 활용 전 입력 토큰수 줄이기 위해
- 연령대, 지역명은 제거 후 속성으로 추가
- 시작/마지막연도가 따로 존재하므로 기간 정보는 단순 제거
- 내용과 큰 연관 없는 정보 단순 제거 (응답유형, 대분류, 전체 등)

In [77]:
df_table_name = df_table[["통계표ID","통계표명"]].copy()
df_table_name

               통계표ID                       통계표명
0          DT_1SA100           세종특별자치시 농가, 농가인구
1          DT_1SA101                  경지규모별 농가수
2         DT_1SA1011                 논면적규모별 농가수
3      DT_1SA1011_01                   농가수, 논면적
4         DT_1SA1013                 밭면적규모별 농가수
...              ...                        ...
11811     DT_1A02038           시도별 · 이동유형별 귀산촌인
11812     DT_1A02039      시도별 · 성별 · 연령별 귀산촌가구주
11813     DT_1A02040     시도별(시군별) · 가구원수별 귀산촌가구
11814     DT_1A02041  시도별(시군별) · 가구 구성형태별 귀산촌가구
11815     DT_1A02042          시도별 · 전입사유별 귀산촌가구

[11816 rows x 2 columns]

#### 1) 단어 빈도수 확인

전체 확인

In [78]:
import pandas as pd
from collections import Counter
import re


# 모든 통계표명 합치기 (소문자 통일 + 특수문자 제거)
all_text = " ".join(df_table["통계표명"].astype(str))
all_text = re.sub(r"[^\w\s]", " ", all_text)  # 특수문자 제거
all_text = all_text.lower()

# 띄어쓰기 기준 단어 분리
tokens = all_text.split()

# 단어 빈도수 계산
word_counts = Counter(tokens)

# 상위 N개 단어 보기
top_n = 1000
for word, count in word_counts.most_common(top_n):
    print(f"{word}: {count}")

및: 2502
시도: 1976
이상: 1264
성별: 1141
인구: 1059
산업: 972
성: 958
농가: 672
연령별: 669
연령: 649
가구: 538
사업체수: 514
시군구: 477
종사자수: 467
규모별: 465
총괄: 413
면적: 406
산업별: 397
일반가구: 394
15세: 388
취업자: 379
15세이상: 346
행정구역: 337
현황: 314
가구당: 308
월평균: 307
어가: 287
13세: 286
종사자규모별: 282
이동: 276
일자리: 268
조직형태별: 268
가구주: 267
교육정도별: 256
대한: 251
가계수지: 251
20세이상: 250
개인농가: 244
수: 243
거처의: 232
종사상지위별: 228
행위자비율: 227
직업: 218
시도별: 215
가구주의: 208
별: 200
전국: 194
혼인상태별: 182
복수응답: 178
2인이상: 174
직업별: 173
임가: 168
전: 163
가구원: 162
거주지별: 159
종류: 157
가구원수별: 143
현거주지: 142
만족도: 141
93: 140
평균시간: 139
시: 138
이민자: 138
매출액: 137
1인가구: 133
행동비율: 133
농가수: 132
주된: 131
현: 131
수확면적: 130
어업: 130
신혼부부: 129
20: 124
행위자평균시간: 124
교육정도: 123
고령자: 123
해수면어업: 123
산업중분류별: 119
종류별: 115
19세: 115
1인이상: 113
산업세세분류별: 110
경영주: 110
재배면적: 109
기업체수: 108
주요지표: 105
주된응답: 105
어가인구: 105
혼인상태: 104
주거전용: 104
통근: 103
가구내구재: 102
취업자의: 101
세대구성: 99
10인: 97
소득: 96
점유형태별: 95
가구수: 93
도시: 92
연간소득: 92
인구의: 92
이유: 90
지난: 90
06: 90
종사자: 89
농가인구: 88
중분류: 88
자산: 88
경제활동상태별: 87
유형별: 87
부채: 87
도별: 85
외국인: 84
05: 84
매출액규모별: 83
경제활동인구: 82
지역별: 82
60세: 81
종사: 81
수확면적규모별: 81
행정리: 80
5세: 79
이동인구: 79
학생: 79
특성별: 79
농가경제: 78
주택: 77
대분류: 76
기혼여성인구: 76
거주지: 76
제조업: 76
시군: 75
산업대분류별: 75
12세: 74
9개도: 74
내수면어업: 74
1년간: 73
산업세세분류: 73
광업: 73
마리: 72
자본금규모별: 72
1인당: 72
사업체구분별: 72
마리수: 72
재배면적규모별: 72
세대구성별: 71
취업여부별: 70
사육규모별: 69
경제활동상태: 67
학생의: 67
상대표준오차: 67
지위별: 66
취업: 66
통학인구: 63
가구원수: 62
여부: 61
취업인구: 60
관련: 60
논벼: 59
평균: 58
사업체: 58
부가가치: 58
기업규모별: 58
변화: 58
보유수량: 58
구산업별: 56
98: 56
총농가: 56
비경제활동인구: 55
농림어업제외: 55
연령대별: 55
군: 54
일: 54
소득5분위별: 54
실질: 54
저축액: 54
5년: 53
농업: 53
어가수: 53
10세이상: 53
견해: 52
구: 51
방과후학교: 51
시계열: 50
임금근로자: 50
100: 50
겸업별: 50
1년: 49
보정: 49
前: 49
자료: 49
재고액: 49
산업소분류: 49
어학연수: 49
f: 49
12세이상: 48
이동자의: 48
인식: 47
학교급별: 47
참여율: 47
주택의: 46
점유형태: 46
비율: 46
산업세분류: 46
종사상: 45
연간판매액: 45
서비스업: 44
급여액: 44
면적규모별: 44
대표자성별: 44
종사자성별: 44
두당: 44
구성비: 43
종업원: 43
기성액: 43
1000가구당: 43
현재: 42
2020: 42
직종별: 42
주: 42
종사기간: 42
경지규모별: 41
형태별: 41
국적: 41
학력별: 41
시설: 41
10세: 41
활동제약: 40
자녀: 40
산업소분류별: 40
응답: 40
재등록자의: 40
모의: 39
읍면동: 39
근속기간별: 39
도소매업: 39
산업분류별: 39
5: 38
출생자녀수별: 38
가장: 38
향후: 38
참여: 38
가계지출: 38
현황별: 38
종사상의: 37
자동차: 37
정도: 37
이혼: 37
충청북도: 36
서울특별시: 36
실업자: 36
초혼: 36
재혼: 36
근로형태별: 36
유형고정자산: 36
배우자: 36
자원봉사활동: 36
생활여건의: 36
장애인: 36
임업: 36
동력선: 36
젖소: 36
사교육비: 36
강원도: 35
전라북도: 35
60세이상: 35
소요시간별: 35
의료서비스: 35
인식도: 35
입주형태별: 35
계층별: 35
교제: 35
임금근로자의: 35
연금: 35
수출입: 35
5년전: 34
부산광역시: 34
대구광역시: 34
인천광역시: 34
광주광역시: 34
대전광역시: 34
울산광역시: 34
충청남도: 34
전라남도: 34
통근통학지별: 34
혼인: 34
2017: 34
근로자: 34
연간급여액: 34
가구분포: 34
재배: 34
생산비: 34
명목: 34
소분류: 33
관계: 33
취업시간별: 33
종사자규모: 33
제주특별자치도: 33
여가활동: 33
수산물: 33
가입률: 33
유업자: 32
통학: 32
보유: 32
인건비: 32
학교생활: 32
부채잔액: 32
어업종사가구원: 32
사용방수: 31
거주기간별: 31
교육: 31
종업원규모별: 31
대표자연령대별: 31
겸업: 31
영주: 31
6세이상: 30
유무: 30
출생: 30
9차: 30
생산액: 30
가족: 30
할: 30
사회안전에: 30
5분위별: 30
연령계층별: 30
사육현황: 30
연말기준: 30
1인: 29
전세금: 29
사글세: 29
고령자인구: 29
국적별: 29
14세이상: 29
중: 29
2000: 29
임차료: 29
종업원수: 29
작성기관별: 29
판매금액별: 29
한우: 29
사회보험: 29
귀화허가자: 29
보증금: 28
종사상지위: 28
희망: 28
환경오염: 28
경영조직: 28
이동자수: 28
생활: 28
수목수: 28
사교육: 28
통근통학: 27
이용교통수단별: 27
수입액: 27
방법: 27
학습: 27
부모: 27
어업종사자수: 27
요일평균: 27
사육: 26
사용방수별: 26
가구주와의: 26
가구의: 26
컴퓨터: 26
총조사인구: 26
영농형태별: 26
기준: 26
영업비용: 26
판매처별: 26
영향: 26
노력: 26
재배농가의: 26
닭: 26
총자산: 26
경영형태별: 25
규모: 25
거주: 25
난방시설별: 25
65세: 25
동거: 25
단독주택: 25
직장: 25
주요: 25
10차: 25
문화: 25
산업중분류: 25
수준: 25
미신고이유: 25
지역: 25
과수: 25
가정관리: 25
임가인구: 24
월세금: 24
초혼연령별: 24
의: 24
외: 24
내: 24
이용: 24
사회활동별: 24
또는: 24
경험: 24
증감: 24
싶은: 24
활동: 24
근로여건: 24
보유율: 24
경제활동별: 24
부채액: 24
돼지: 24
학생이외: 24
기혼여자의: 24
돌보기: 24
근무지기준: 24
4: 24
유학생: 24
행정구역별: 23
거주가구: 23
주거시설: 23
다문화: 23
20세: 23
연간: 23
본: 23
사업장면적: 23
부모의: 23
수익성: 23
도소매: 23
기업수: 23
한국: 23
자산5분위별: 23
순자산5분위별: 23
목적지별: 22
근로장소별: 22
보육상태별: 22
아동인구: 22
6세: 22
주택소유: 22
15세이상인구: 22
근로: 22
위한: 22
졸업: 22
소득구간별: 22
숙박음식점업: 22
5명이상: 22
전반적인: 22
호텔업: 22
제도부문별: 22
산란계: 22
방법별: 22
용도별: 22
사육비: 22
개인대출: 22
조직형태간: 22
기업규모간: 22
산업대분류간: 22
종사상지위간: 22
참여비용: 22
가구특성별: 22
개인특성별: 22
성비: 21
활동제약유형별: 21
출생지별: 21
생활비: 21
경력단절여성인구: 21
사망자수: 21
등: 21
가입현황: 21
평소: 21
세세분류: 21
숙박: 21
조직형태: 21
산업세분류별: 21
출하: 21
10명: 21
복수: 21
가족관계: 21
농기계: 21
주종사분야별: 21
고추: 21
육계: 21
마을수: 21
판매농가와: 21
맞벌이가구: 21
농업법인: 21
ebs: 21
일상: 20
보유현황별: 20
출생아: 20
여자: 20
총조사가구: 20
교통수단: 20
시군구별: 20
활용: 20
시군별: 20
임가공품목별: 20
방지노력: 20
부담에: 20
2: 20
업종별: 20
보유가구비율: 20
양식품종별: 20
신생: 20
소멸: 20
방문취업: 20
재외동포: 20
가계재무건전성: 20
담보부채: 20
신용부채: 20
상세현황: 20
인터넷: 19
출생아수별: 19
출생지: 19
연건평: 19
각세별: 19
분야별: 19
근로여건만족도: 19
맞벌이: 19
연령계층: 19
종사분야: 19
척수: 19
임산물: 19
지대별: 19
2009년: 19
평일: 19
연체율: 19
퇴직연금제도: 19
h: 19
영업겸용: 18
1년전: 18
동거여부: 18
주택의종류: 18
0: 18
다문화가구: 18
가구구분별: 18
활동상태별: 18
주당: 18
장래: 18
점포수: 18
자본금규모: 18
연말재고액: 18
통계인력: 18
원도급: 18
하도급공사: 18
미기성액: 18
해외건설: 18
재학생: 18
흡연과: 18
불만이유: 18
사회보험료: 18
늘려야: 18
복지서비스: 18
20세이상인구: 18
1: 18
정보화현황별: 18
종사형태: 18
육우: 18
어획품종별: 18
논: 18
영농형태: 18
학생과: 18
월평균소득별: 18
어업법인: 18
종사자지위별: 18
경력단절여성: 18
거주지역: 18
학년: 18
세종특별자치시: 17
복숭아: 17
비농가별: 17
1세: 17
보유현황: 17
사유: 17
농산물: 17
지점별: 17
자본금: 17
경영조직별: 17
판매액: 17
산업분류: 17
품목분류별: 17
공사지역: 17
체감환경: 17
후: 17
어려운: 17
정보화의: 17
초등학교: 17
자산현황: 17
10분위별: 17
품종: 17
어로어업: 17
한육우: 17
임금수준별: 17
가입자: 17
순자산: 17
주택수: 16
관계별: 16
총방수별: 16
지위: 16
구시군: 16
부인수: 16
월세금별: 16
5년전거주지별: 16
일상생활: 16
추이: 16
유무별: 16
그만둔: 16
신규: 16
품목별: 16
소비구간별: 16
세분류: 16
계약액: 16
있다: 16
기부: 16
차별: 16
봉사활동: 16
직능별: 16
가구유형별: 16
소득종류별: 16
농축산물: 16
거처형태별: 16
양파: 16
마늘: 16
사과: 16
배: 16
경영규모별: 16
준농가: 16
경지규모: 16
수당: 16
함께한: 16
사람별: 16
전공계열별: 16
개인사업자의: 16
주산지시군: 16
한국에서: 16
한국계외국인: 16
논면적: 15
경지면적: 15
여성인구: 15
있는: 15
어머니의: 15
도: 15
남자: 15
1년전거주지별: 15
교통수단별: 15
대학: 15
기간별: 15
연면적: 15
국민연금: 15
중퇴: 15
받은: 15
소득10분위별: 15
출하액규모별: 15
고: 15
쓰레기: 15
원인: 15
지출액: 15
000가구당: 15
경지면적에: 15
비율별: 15
보유농가: 15
콩: 15
포도: 15
종사부문: 15
양식방법별: 15
법인수: 15
자회사: 15
취업가구: 15
기업체: 15
구매: 15
대출: 15
무급: 15
가사노동: 15
평가액: 15
육아휴직: 15
거처종류별: 14
활용상태별: 14
연도: 14
내국인: 14
근무연수별: 14
거주가구수별: 14
창업: 14
비임금: 14
운영: 14
비중: 14
횟수: 14
표본오차: 14
효과: 14
사용: 14
태도: 14
문제: 14
건강평가: 14
가구소득: 14
사회의: 14
계층이동: 14
피고용자수: 14
대표자남여별: 14
종사자남여별: 14
생산자조직: 14
보유어선: 14
밭: 14
수확농가: 14
시간: 14
행동별: 14
19세이상: 14
사망원인: 14
출산: 14
대출잔액: 14
가구_시도: 14
비전문취업: 14
밭면적: 13
채소: 13
기타: 13
임가수: 13
전공분야별: 13
남편의: 13
구성: 13
총: 13
집: 13
사유별: 13
계절조정: 13
임금근로: 13
산재보험: 13
맞벌이여부별: 13
사업장면적규모별: 13
소유형태별: 13
발주자별: 13
학교교육의: 13
본인의: 13
운수비용: 13
프랜차이즈: 13
시설면적: 13
쌀보리: 13
품종별: 13
양식장: 13
수원지: 13
취업별: 13
생산량: 13
생체: 13
경영상황: 13
사업형태별: 13
신생기업: 13
사업소득: 13
가입: 13
주택종류별: 12
학교: 12
거처의종류: 12
보유대수별: 12
추가계획자녀수별: 12
보유가구: 12
생활비원천별: 12
65세이상: 12
거처의종류별: 12
이하: 12
12세이하: 12
현재국적별: 12
출산기간별: 12
실업률: 12
전체: 12
의사: 12
취업분포: 12
음식점업: 12
여가활용: 12
하는: 12
사회적: 12
30세: 12
원하는: 12
교육비: 12
물: 12
생존: 12
두려움: 12
우선적으로: 12
인지도: 12
노후준비방법: 12
pc통신: 12
비교: 12
공중질서수준: 12
사회문제에: 12
장비대수: 12
보유대수: 12
휴양콘도운영업: 12
정기휴무일수별: 12
일일평균: 12
여가관련: 12
연간경상소득: 12
참깨: 12
떫은감: 12
이외: 12
톤수규모별: 12
비육돈: 12
어업경영주: 12
어업가구: 12
개인유지: 12
학생이외의: 12
참여활동: 12
체류자격별: 12
종사지위별: 12
고졸이상: 12
생존율: 12
구간별: 12
변동전: 12
임금수준간: 12
아버지의: 12
순자본스톡: 12
생산자본스톡: 12
야간: 11
전세금별: 11
보증금별: 11
사회: 11
적생아: 11
5세이상: 11
재학: 11
14세: 11
분기: 11
1992: 11
사망률: 11
여부별: 11
최근: 11
이직: 11
소속: 11
사업체의: 11
비정규직: 11
않은: 11
고용률: 11
건물연면적규모별: 11
매출액규모: 11
주요생산비: 11
사람: 11
어려움: 11
관계망: 11
환경: 11
마련: 11
분야: 11
농약오염에: 11
불안: 11
친환경: 11
근로시간: 11
민원서비스: 11
중복응답: 11
점: 11
아동: 11
백화점: 11
사회복지: 11
5세별: 11
종사인원별: 11
수확: 11
봉: 11
단감: 11
노지: 11
어업형태별: 11
재배농가: 11
면적과: 11
농가부채: 11
경영개황: 11
어항시설: 11
가구별: 11
기업: 11
에서: 11
거주지역별: 11
신혼부부의: 11
금융권: 11
교재: 11
소득분위별: 11
전겸업별: 10
5세계급: 10
가구형태별: 10
행정리수: 10
부부의: 10
근무년수별: 10
사글세별: 10
부인: 10
경제활동: 10
포함: 10
인구규모별: 10
배우관계: 10
외국인수: 10
상태: 10
근무: 10
정보: 10
출산자녀수별: 10
취업자수: 10
기간: 10
사업자등록비율: 10
취업시간: 10
비임금근로자: 10
근속기간: 10
소비자물가지수: 10
기타경비: 10
판매방법별: 10
건물: 10
출하액: 10
국내: 10
여가: 10
불만족: 10
미치는: 10
준수: 10
다른: 10
방지: 10
운전습관: 10
환경문제: 10
부모와의: 10
않는: 10
사항: 10
음주와: 10
범죄피해에: 10
공공시설: 10
통계표: 10
관한: 10
환경오염에: 10
체감: 10
대기오염: 10
지역문화예술행사: 10
등과: 10
사업장: 10
연간소득계층별: 10
가구주연령계층별: 10
2인이상가구: 10
목초지면적: 10
사업별: 10
겉보리: 10
약용작물: 10
소재지: 10
종사분야별: 10
어업종사기간별: 10
경지: 10
생산농가의: 10
주요투입물량: 10
소득분석: 10
행동분류별: 10
따른: 10
음식주점: 10
도매및소매업: 10
대표자: 10
주택소유별: 10
개인형: 10
irp: 10
적립금액: 10
등록취업자의: 10
수준별: 10
고등학교: 10
교재비: 10
체류자격: 10
만족도별: 10
한국어: 10
한국사회: 10
점유율: 10
과수원면적: 9
일반가구수: 9
가구주연령별: 9
거주인수별: 9
소요시간: 9
경기: 9
취업상태: 9
육체적: 9
정신적: 9
활동제약자: 9
정보통신기기: 9
출생아수: 9
취업상태별: 9
연수별: 9
수별: 9
주차장소별: 9
사망: 9
2008: 9
취업경험: 9
직장의: 9
계획: 9
유연근무제: 9
미취업자: 9
건물연면적: 9
판매액규모별: 9
10명이상: 9
등록업종별: 9
18세: 9
온라인: 9
정보화: 9
것: 9
전과: 9
음주: 9
국가: 9
확대: 9
복지사업: 9
자녀와: 9
받고: 9
분포: 9
운수업: 9
건물면적규모별: 9
영업시간별: 9
거래: 9
도입: 9
주거전용면적별: 9
목초지: 9
고용기간: 9
고용인수별: 9
처리방법별: 9
팥: 9
감자: 9
배추: 9
산나물: 9
표고버섯: 9
시설작물: 9
양식면적: 9
출어일수별: 9

괄호 내용 확인

In [79]:
import re
from collections import Counter

# 전체 텍스트 결합 (통계표명 컬럼 전체)
all_text = " ".join(df_table["통계표명"].astype(str))

# 괄호 안 단어 추출: (단어)
bracket_words = re.findall(r"\((.*?)\)", all_text)

# 빈도수 계산
bracket_counts = Counter(bracket_words)

# 상위 N개 출력
top_n = 100
for word, count in bracket_counts.most_common(top_n):
    print(f"{word}: {count}")

개인농가: 244
일반가구: 243
15세 이상: 215
15세이상: 213
시도: 172
해수면어업: 123
’20~ : 120
이민자: 99
2인이상 가구: 96
10인 이상: 92
중분류: 84
`93~`05: 84
농가경제: 78
13세 이상 인구: 76
대분류: 74
내수면어업: 73
9개도: 72
`06~  : 67
일반가구, 주거전용: 63
12세 이상: 60
'93-'98: 56
농림어업제외: 55
총농가: 55
60세 이상: 52
20세이상: 50
시계열 보정 前 자료: 46
1인가구: 46
19세 이상: 45
5세 이상: 44
복수응답: 44
전국,1인이상: 42
도시,1인이상: 42
주거전용: 40
가구주: 39
20세이상 인구: 38
시도/시/군/구: 37
소분류: 33
영주(F-5: 30
5세: 28
주된응답: 28
12세이상: 26
20세이상, 일반가구: 26
전국,2인이상: 26
도시,2인이상: 26
19세 이상 인구: 26
10세 이상: 26
2020=100: 25
근무지기준: 24
6세이상: 23
10차: 22
15세 이상 취업자: 22
65세 이상: 21
세세분류: 21
주된응답, 13세 이상 인구: 21
복수응답, 13세 이상 인구: 21
60세이상: 20
활동/신생/소멸: 20
명목, 연말기준: 20
F-4: 19
2009년: 18
읍면동/성/연령별: 17
`06~   : 17
세분류: 16
5명이상: 16
지난 1년간, 복수응답, 13세 이상 인구: 16
준농가: 16
13세 이상: 15
15세이상인구: 15
10세: 15
6세 이상: 14
9차: 14
전국,1인이상,실질: 14
도시,1인이상,실질: 14
시군구: 14
명목: 14
지난 1년간, 이민자: 14
1세 이상: 13
20세 이상 인구: 13
65세이상: 12
14세이상: 12
12세이하, 일반가구: 12
고졸이상: 12
변동전: 12
비전문취업: 12
시군별: 12
구시군: 11
5세이상: 11
9차, ~2017: 11
15세이상 인구: 11
중복응답: 11
봉: 11
2020=100.0: 11
복수응답, 이민자: 11
방문취업(H-2: 11
5세계급: 10
소속: 10
지난 1년간, 13세 이상 인구: 10
15세 이상 인구: 10
실질, 연말기준: 10
영업겸용: 9

#### 2) 지역명 제거

In [80]:
df_txt = pd.read_csv("./raw_data/법정동코드 전체자료.txt", sep="\t", encoding="cp949")

region_set = set()

for name in df_txt["법정동명"].values:
    parts = name.strip().split()
    if len(parts) == 1:
        region_set.add(parts[0])
    elif len(parts) >= 2:
        if parts[0].endswith("시"):
            region_set.add(parts[0])
        else:
            region_set.add(parts[0])
            region_set.add(parts[1])


manual_regions = [
    "전국", "서울", "인천", "경기", "대구", "경북", "광주",
    "전남", "대전", "충북", "충남", "강원", "전북", "제주"
]

# 정규식 패턴 생성
left_boundary = r"(^|[ ,()·])"
right_boundary = r"(?=[ ,()·]|$)"

region_pattern1 = left_boundary + "(" + "|".join(sorted(region_set, key=len, reverse=True)) + ")" + right_boundary
region_pattern2 = left_boundary + "(" + "|".join(map(re.escape, manual_regions)) + ")" + right_boundary



# 4. 함수 정의: 두 패턴 모두에서 지역 추출 및 제거
def extract_regions_sequential(text):
    found_regions = set()

    # pattern1 적용
    matches1 = re.findall(region_pattern1, text)
    for match in matches1:
        found_regions.add(match[1])  # 두 번째 그룹이 실제 지역명
        text = re.sub(re.escape(match[1]), "", text)

    # pattern2 적용 (pattern1 제거 후 텍스트에)
    matches2 = re.findall(region_pattern2, text)
    for match in matches2:
        found_regions.add(match[1])
        text = re.sub(re.escape(match[1]), "", text)

    return pd.Series([", ".join(sorted(found_regions)), text.strip()])

# 적용
df_table_name[["지역", "cleaning1"]] = df_table_name["통계표명"].astype(str).apply(extract_regions_sequential)

In [81]:
import re

def clean_region_name(region):
    if pd.isna(region):
        return region

    # 1. 광역시, 특별자치시, 특별자치도 삭제
    region = re.sub(r"(광역시|특별자치시|특별자치도)", "", region)

    # 2. 충청남도 → 충남, 충청북도 → 충북 등 축약
    region = region.replace("충청남도", "충남").replace("충청북도", "충북")
    region = region.replace("경상남도", "경남").replace("경상북도", "경북")
    region = region.replace("전라남도", "전남").replace("전라북도", "전북")
    region = region.replace("강원도", "강원").replace("제주도", "제주")

    # 3. 앞뒤 공백 제거
    return region.strip()

# 적용
df_table_name["지역"] = df_table_name["지역"].astype(str).apply(clean_region_name)

In [82]:
df_filtered = df_table_name[df_table_name["지역"].str.strip() != ""]
df_filtered

,통계표ID,통계표명,지역,cleaning1
0,DT_1SA100,"세종특별자치시 농가, 농가인구",세종,"농가, 농가인구"
90,DT_1B9000D,"현거주지/성/목적지별 통근·통학인구(서울,인천,경기,12세이상)","경기, 서울, 인천","현거주지/성/목적지별 통근·통학인구(,,,12세이상)"
92,DT_1B9000F,"현거주지/성/목적지별 통근·통학인구(대구,경북,12세이상)","경북, 대구","현거주지/성/목적지별 통근·통학인구(,,12세이상)"
93,DT_1B9000G,"현거주지/성/목적지별 통근·통학인구(광주,전남,12세이상)","광주, 전남","현거주지/성/목적지별 통근·통학인구(,,12세이상)"
94,DT_1B9000H,"현거주지/성/목적지별 통근·통학인구(대전,충남,12세이상)","대전, 충남","현거주지/성/목적지별 통근·통학인구(,,12세이상)"
...,...,...,...,...
11013,INH_1K52B06_39,제주특별자치도 · 산업 · 종사자성별 종사자수(`06~ ),제주,· 산업 · 종사자성별 종사자수(`06~ )
11014,INH_1K52C04_39,제주특별자치도·산업·종사상지위별 종사자수,제주,·산업·종사상지위별 종사자수
11015,INH_1K52C05_39,제주특별자치도·산업·대표자성별 사업체수,제주,·산업·대표자성별 사업체수
11016,INH_1K52C06_39,제주특별자치도·산업·종사자성별 사업체수,제주,·산업·종사자성별 사업체수
11017,INH_1K52C07_39,제주특별자치도·산업·대표자연령대별 사업체수,제주,·산업·대표자연령대별 사업체수

#### 3) 수록기간 제거

In [83]:
import re
from collections import Counter

period_pattern = r"\(['’`]\d{2}[~-][^)]*\)"

all_text = " ".join(df_table["통계표명"].astype(str))
matches = re.findall(period_pattern, all_text)

counted = Counter(matches)

for bracket_str, cnt in counted.most_common():
    print(f"{bracket_str}: {cnt}회")

(’20~ ): 120회
(`93~`05): 84회
(`06~  ): 67회
('93-'98): 56회
(`06~   ): 17회
(’06~ ): 6회
(’16~ ): 2회
('12~   ): 1회
(’12~ ): 1회

In [84]:
def remove_pattern(text):
    return re.sub(period_pattern, "", text)

df_table_name["cleaning2"] = df_table_name["cleaning1"].astype(str).apply(remove_pattern)

changed_rows = df_table_name[df_table_name["cleaning2"].astype(str) != df_table_name["cleaning1"].astype(str)]

# 결과 출력
changed_rows[["통계표명","cleaning1","cleaning2"]]

,통계표명,cleaning1,cleaning2
5739,시도별/구산업별/사업체구분별('93-'98),시도별/구산업별/사업체구분별('93-'98),시도별/구산업별/사업체구분별
5740,시도별/구산업별/조직형태별('93-'98),시도별/구산업별/조직형태별('93-'98),시도별/구산업별/조직형태별
5741,시도별/구산업별/종사자규모별('93-'98),시도별/구산업별/종사자규모별('93-'98),시도별/구산업별/종사자규모별
5742,시도별/구산업별/종사상지위별('93-'98),시도별/구산업별/종사상지위별('93-'98),시도별/구산업별/종사상지위별
5743,"시도/산업/사업체구분별 사업체수, 종사자수(`93~`05)","시도/산업/사업체구분별 사업체수, 종사자수(`93~`05)","시도/산업/사업체구분별 사업체수, 종사자수"
...,...,...,...
11009,"제주특별자치도 · 산업 · 조직형태별 사업체수, 종사자수(`06~ )","· 산업 · 조직형태별 사업체수, 종사자수(`06~ )","· 산업 · 조직형태별 사업체수, 종사자수"
11010,"제주특별자치도 · 산업 · 종사자규모별 사업체수, 종사자수(`06~ )","· 산업 · 종사자규모별 사업체수, 종사자수(`06~ )","· 산업 · 종사자규모별 사업체수, 종사자수"
11011,"제주특별자치도 · 산업 · 종사자지위별, 종사자수(`06~ )","· 산업 · 종사자지위별, 종사자수(`06~ )","· 산업 · 종사자지위별, 종사자수"
11012,제주특별자치도 · 산업 · 대표자성별 사업체수(`06~ ),· 산업 · 대표자성별 사업체수(`06~ ),· 산업 · 대표자성별 사업체수
11013,제주특별자치도 · 산업 · 종사자성별 종사자수(`06~ ),· 산업 · 종사자성별 종사자수(`06~ ),· 산업 · 종사자성별 종사자수

#### 4) 연령대 제거

In [85]:
import re
from collections import Counter

age_pattern = r"\d{1,3}세\s?(?:이상|이하|미만|초과)"

text = " ".join(df_table["통계표명"].astype(str))
matches = re.findall(age_pattern, text)
full_bases = {re.match(r"\d{1,3}세", m).group() for m in matches}
counted_full = Counter(matches)

# 출력
for k, v in counted_full.most_common():
    print(f"{k}: {v}회")

15세 이상: 387회
15세이상: 368회
13세 이상: 286회
20세이상: 276회
19세 이상: 115회
60세 이상: 79회
12세 이상: 63회
10세이상: 54회
5세 이상: 51회
12세이상: 48회
60세이상: 35회
14세이상: 33회
6세이상: 30회
10세 이상: 26회
65세 이상: 24회
20세 이상: 23회
6세 이상: 22회
1세 이상: 16회
19세이상: 14회
65세이상: 12회
12세이하: 12회
30세 이상: 12회
5세이상: 11회
14세 이상: 8회
1세이상: 7회
12세 이하: 6회
10세이하: 5회
18세 미만: 5회
18세이상: 4회
30세이상: 4회
13세이상: 3회
7세이상: 3회
0세 이상: 3회
18세 이하: 2회
18세 이상: 2회
2세이하: 1회
24세 이하: 1회
0세이상: 1회
40세 이상: 1회

In [86]:
sum(counted_full.values())

2053

In [87]:
import re
import pandas as pd

pattern_full = r"\d{1,3}세\s?(?:이상|이하|미만|초과)"
# pattern_simple = r"[ ,()·]\d{1,3}세"

def extract_and_clean_age(text):
    found_ages = []

    # 1. pattern_full 찾기
    matches_full = re.findall(pattern_full, text)
    found_ages.extend(matches_full)

    # 1-1. pattern_full 제거
    cleaned = text
    for m in matches_full:
        cleaned = re.sub(re.escape(m), "", cleaned)

    # 2. pattern_simple 찾기 (pattern_full 제거된 텍스트에서)
    # matches_simple = re.findall(pattern_simple, cleaned)
    # found_ages.extend(matches_simple)

    # 2-1. pattern_simple 제거
    # for m in matches_simple:
    #     cleaned = re.sub(r"\b" + re.escape(m) + r"\b", "", cleaned)

    # 연령대는 중복 제거 후 쉼표로 연결
    found_ages = sorted(set(found_ages))

    return pd.Series([", ".join(found_ages), cleaned.strip()])

# 적용
df_table_name[["연령대", "cleaning3"]] = df_table_name["cleaning2"].astype(str).apply(extract_and_clean_age)

In [88]:
# 빈 괄호 또는 괄호 안에 문자열이 하나만 있는 경우 삭제

def remove_parentheses(text):
    return re.sub(r"\([^)]{0,1}\)", "", text)

df_table_name["cleaning3"] = df_table_name["cleaning3"].astype(str).apply(remove_parentheses)

In [89]:
# 결과 확인
df_filtered = df_table_name[df_table_name["연령대"].str.strip() != ""]
df_filtered[["통계표명", "연령대", "cleaning3"]]

,통계표명,연령대,cleaning3
66,성별/연령별/혼인상태별 1인가구수(15세이상),15세이상,성별/연령별/혼인상태별 1인가구수
69,성별/연령별/교육정도별 인구(6세이상),6세이상,성별/연령별/교육정도별 인구
70,성별/연령별/혼인상태별 인구(15세이상),15세이상,성별/연령별/혼인상태별 인구
83,행정구역/가구규모/성별 통근·통학인구(12세이상),12세이상,행정구역/가구규모/성별 통근·통학인구
84,대도시/통근통학/성/이용교통수단별 통근·통학인구(12세이상),12세이상,대도시/통근통학/성/이용교통수단별 통근·통학인구
...,...,...,...
9841,"녹색생활 실천하는 이유(녹색생활 실천하는 사람, 20세이상 인구)",20세이상,"녹색생활 실천하는 이유(녹색생활 실천하는 사람, 인구)"
9842,"녹색생활 실천하지 않는 이유(녹색생활 실천하지 않는 사람, 20세이상 인구)",20세이상,"녹색생활 실천하지 않는 이유(녹색생활 실천하지 않는 사람, 인구)"
11347,15세 이상 국내 상주인구(이민자),15세 이상,국내 상주인구(이민자)
11733,개인특성별 경제활동상태별 15세이상 인구,15세이상,개인특성별 경제활동상태별 인구
11747,개인특성별 노후준비별 인구(만40세 이상),40세 이상,개인특성별 노후준비별 인구

#### 5) 기타
- 응답유형 제거 : 주된응답, 복수응답 등
- 분류유형 제거 : 소분류, 중분류, 대·중분류 등
- 포괄적인 단어 제거 : 전체, 전국

In [90]:
import re

pattern = (
    r"(주된\s?응답|복수\s?응답|단일\s?응답|다중\s?응답|미응답|무응답),?\s?"  # 응답 유형 제거
    r"|" 
    r"\([^\s)]{1,3}분류\)"                       # 괄호 안 글자 최대 3자 + 분류 제거
    r"|" 
    r"(\(전체\),|-\s?전체|\(전국\),|-\s?전국)"     # 전체/전국 단어 제거
)

def remove_terms(text):
    return re.sub(pattern, "", text)

df_table_name["cleaning4"] = df_table_name["cleaning3"].astype(str).apply(remove_terms)

In [91]:
# 괄호 제거
df_table_name["cleaning4"] = df_table_name["cleaning4"].astype(str).apply(remove_parentheses)

In [92]:
# 결과 출력
changed_rows = df_table_name[df_table_name["cleaning4"].astype(str) != df_table_name["cleaning3"].astype(str)]

display(changed_rows[["통계표ID","cleaning3","cleaning4"]])

,통계표ID,cleaning3,cleaning4
147,DT_1BAOO03,시도/성/직업(대분류)/산업(대분류)별 취업자,시도/성/직업/산업별 취업자
148,DT_1BAOO04,행정구역/성/연령/산업(대분류)별 취업자,행정구역/성/연령/산업별 취업자
149,DT_1BAOO05,행정구역/성/연령/직업(대분류)별 취업자,행정구역/성/연령/직업별 취업자
152,DT_1BAOO08,"시도/성/연령,혼인상태/산업(대분류)별 취업자","시도/성/연령,혼인상태/산업별 취업자"
153,DT_1BAOO09,"시도/성/연령,혼인상태/직업(대분류)별 취업자","시도/성/연령,혼인상태/직업별 취업자"
...,...,...,...
11441,DT_2FP008R,"한국생활에서 어려운 사항(복수응답, 이민자)",한국생활에서 어려운 사항(이민자)
11443,DT_2FP010R,"여가 활용 형태(복수응답, 이민자)",여가 활용 형태(이민자)
11455,DT_2FQ002R,"한국어 학습 경험 유무 및 학습기관(복수응답, 이민자)",한국어 학습 경험 유무 및 학습기관(이민자)
11471,DT_2FR007R,"취업할 때 일자리 정보 획득 경로(복수응답, 방문취업(H-2), 재외동포(F-4) ...","취업할 때 일자리 정보 획득 경로(방문취업(H-2), 재외동포(F-4) 한국계외국인)"
11474,DT_2FR010R,"한국 내 직장(사업체)에서 경험한 사항들(지난 1년간, 복수응답, 방문취업(H-2)...","한국 내 직장(사업체)에서 경험한 사항들(지난 1년간, 방문취업(H-2), 재외동포..."

새로운 속성 "지역", "연령대"를 기존 df에 적용

In [93]:
df_table["지역"]=df_table_name["지역"]
df_table["연령대"]=df_table_name["연령대"]

df_table

,통계표ID,통계표명,승인번호,기관코드,주기,시작연도,마지막연도,지역,연령대
0,DT_1SA100,"세종특별자치시 농가, 농가인구",13002,101,부정기,2013,2013,세종,
1,DT_1SA101,경지규모별 농가수,13002,101,부정기,2013,2013,,
2,DT_1SA1011,논면적규모별 농가수,13002,101,부정기,2013,2013,,
3,DT_1SA1011_01,"농가수, 논면적",13002,101,부정기,2013,2013,,
4,DT_1SA1013,밭면적규모별 농가수,13002,101,부정기,2013,2013,,
...,...,...,...,...,...,...,...,...,...
11811,DT_1A02038,시도별 · 이동유형별 귀산촌인,930002,101,년,2018,2023,,
11812,DT_1A02039,시도별 · 성별 · 연령별 귀산촌가구주,930002,101,년,2018,2023,,
11813,DT_1A02040,시도별(시군별) · 가구원수별 귀산촌가구,930002,101,년,2018,2023,,
11814,DT_1A02041,시도별(시군별) · 가구 구성형태별 귀산촌가구,930002,101,년,2018,2023,,
11815,DT_1A02042,시도별 · 전입사유별 귀산촌가구,930002,101,년,2018,2023,,

### 2. 구분 및 대상 추출
- ex) 산업별 취업자 -> 구분: 산업, 대상: 취업자

In [94]:
# 상위 빈도 단어 중에서 '별'로 끝나는 단어만 필터링
top_n = 150  # 필요 시 조절
별로_끝나는_단어 = [(word, count) for word, count in word_counts.most_common(top_n) if word.endswith("별")]

# 출력
for word, count in 별로_끝나는_단어:
    print(f"{word}: {count}")

성별: 1141
연령별: 669
규모별: 465
산업별: 397
종사자규모별: 282
조직형태별: 268
교육정도별: 256
종사상지위별: 228
시도별: 215
별: 200
혼인상태별: 182
직업별: 173
거주지별: 159
가구원수별: 143
산업중분류별: 119
종류별: 115
산업세세분류별: 110
점유형태별: 95
경제활동상태별: 87
유형별: 87
도별: 85
매출액규모별: 83
지역별: 82
수확면적규모별: 81
특성별: 79
산업대분류별: 75
자본금규모별: 72
사업체구분별: 72
재배면적규모별: 72
세대구성별: 71
취업여부별: 70
사육규모별: 69

규모별의 경우 종류가 다양하였음 : 종사자규모별, 매출액규모별, 수화면적규모별, 재배면적규모별, 사육규모별 ...

In [95]:
# "규모별" 포함 단어들 총합 계산
규모별_포함_총합 = sum(count for word, count in 별로_끝나는_단어 if "규모별" in word)
포함_단어들 = [(word, count) for word, count in 별로_끝나는_단어 if "규모별" in word]

# "규모별" 미포함 단어들의 개수와 총합 계산
나머지_단어들 = [(word, count) for word, count in 별로_끝나는_단어 if "규모별" not in word]
나머지_개수 = len(나머지_단어들)
나머지_총합 = sum(count for _, count in 나머지_단어들)

print(f'"규모별" 포함 단어 총합: {규모별_포함_총합}회')
print(f'"규모별" 미포함 단어 개수: {나머지_개수}개')
print(f'"규모별" 미포함 단어 총합: {나머지_총합}회')

print("\n[규모별 포함 단어 목록]")
for word, count in 포함_단어들:
    print(f"{word}: {count}회")

"규모별" 포함 단어 총합: 1124회
"규모별" 미포함 단어 개수: 25개
"규모별" 미포함 단어 총합: 5178회

[규모별 포함 단어 목록]
규모별: 465회
종사자규모별: 282회
매출액규모별: 83회
수확면적규모별: 81회
자본금규모별: 72회
재배면적규모별: 72회
사육규모별: 69회

In [96]:
df_table

,통계표ID,통계표명,승인번호,기관코드,주기,시작연도,마지막연도,지역,연령대
0,DT_1SA100,"세종특별자치시 농가, 농가인구",13002,101,부정기,2013,2013,세종,
1,DT_1SA101,경지규모별 농가수,13002,101,부정기,2013,2013,,
2,DT_1SA1011,논면적규모별 농가수,13002,101,부정기,2013,2013,,
3,DT_1SA1011_01,"농가수, 논면적",13002,101,부정기,2013,2013,,
4,DT_1SA1013,밭면적규모별 농가수,13002,101,부정기,2013,2013,,
...,...,...,...,...,...,...,...,...,...
11811,DT_1A02038,시도별 · 이동유형별 귀산촌인,930002,101,년,2018,2023,,
11812,DT_1A02039,시도별 · 성별 · 연령별 귀산촌가구주,930002,101,년,2018,2023,,
11813,DT_1A02040,시도별(시군별) · 가구원수별 귀산촌가구,930002,101,년,2018,2023,,
11814,DT_1A02041,시도별(시군별) · 가구 구성형태별 귀산촌가구,930002,101,년,2018,2023,,
11815,DT_1A02042,시도별 · 전입사유별 귀산촌가구,930002,101,년,2018,2023,,

In [97]:
df_table.to_csv("./nodes/node_table.csv", index=False, encoding="utf-8-sig")

#### [문제점 및 계획]

- 정규식으로 제거하기 까다로움 

    "-별"로 반드시 끝나지 않고 여러개의 구분기준들이 특수기호로 이어진 경우가 많았음
- 주요 구분 단어

    keywords = ["성별","연령별","산업별","시도별","조직형태별","교육정도별","행정구역별","종사상지위별",
            "혼인상태별","직업별","거주지별","가구원수별","점유형태별","경제활동상태별","매출액규모별"]

- To do list
1. df_table_name["cleaning4"]의 각 데이터를 입력값으로 하여 "구분", "대상"을 출력값으로 하는 프롬프트 템플릿 제작
2. 템플릿을 config.yaml에 저장
3. llm 적용하여 잘 실행되는지 확인
4. "구분", "대상"을 df_table_name의 새로운 속성으로 만들기

In [98]:
df_table_name[["통계표ID","통계표명","cleaning4"]]

               통계표ID                       통계표명                  cleaning4
0          DT_1SA100           세종특별자치시 농가, 농가인구                   농가, 농가인구
1          DT_1SA101                  경지규모별 농가수                  경지규모별 농가수
2         DT_1SA1011                 논면적규모별 농가수                 논면적규모별 농가수
3      DT_1SA1011_01                   농가수, 논면적                   농가수, 논면적
4         DT_1SA1013                 밭면적규모별 농가수                 밭면적규모별 농가수
...              ...                        ...                        ...
11811     DT_1A02038           시도별 · 이동유형별 귀산촌인           시도별 · 이동유형별 귀산촌인
11812     DT_1A02039      시도별 · 성별 · 연령별 귀산촌가구주      시도별 · 성별 · 연령별 귀산촌가구주
11813     DT_1A02040     시도별(시군별) · 가구원수별 귀산촌가구     시도별(시군별) · 가구원수별 귀산촌가구
11814     DT_1A02041  시도별(시군별) · 가구 구성형태별 귀산촌가구  시도별(시군별) · 가구 구성형태별 귀산촌가구
11815     DT_1A02042          시도별 · 전입사유별 귀산촌가구          시도별 · 전입사유별 귀산촌가구

[11816 rows x 3 columns]

## 구분/대상 추출

In [169]:
import os
import yaml
import time
from dotenv import load_dotenv
from openai import OpenAI


# 🔹 CLOVA API, URL 로드
load_dotenv()
CLOVA_API_KEY = os.getenv("CLOVASTUDIO_API_KEY")
BASE_URL = os.getenv("CLOVASTUDIO_API_BASE_URL")


# 🔹 프롬프트 템플릿 로드
with open("config.yaml", "r", encoding="utf-8") as f:
    config = yaml.load(f, Loader=yaml.FullLoader)
PROMPT_TEMPLATE_1 = config["criteria_extraction_template"]
PROMPT_TEMPLATE_2 = config["target_extraction_template"]

# 🔹 OpenAI 호환 client 구성
client = OpenAI(
    api_key=CLOVA_API_KEY,
    base_url=BASE_URL
)
def execute_clovastudio(user_input: str, prompt_template: str) -> str:
    prompt = prompt_template.format(table_name=user_input)

    response = client.chat.completions.create(
        model="HCX-005",
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    # time.sleep(0.1)
    return response.choices[0].message.content

In [ ]:
# test

user_input = df_table_name["cleaning4"].values[11814]
criteria = execute_clovastudio(user_input, PROMPT_TEMPLATE_1)
target = execute_clovastudio(user_input, PROMPT_TEMPLATE_2)

print('[input]:',user_input)
print('[criteria]:',criteria)
print('[target]:',target)

[input]: 시도별(시군별) · 가구 구성형태별 귀산촌가구
[criteria]: 행정구역별, 가구 구성형태별
[target]: 귀산촌가구

### Clova Studio API 호출 속도 최적화
- 429 Too Many Requests 에러가 반복적으로 발생
- QPS 제한(초당 요청 수 제한)이 있음
- 요청 60건마다 time.sleep()을 사용해 속도 제한을 인위적으로 적용
- 경과 시간(초)이 호출 수(idx)보다 빠르면 차이값 만큼 대기.
- 요청 간 평균 처리 속도를 1초당 1건으로 유지
- cf) 60 QPM(분당 요청 수)은 1 QPS를 의미

In [173]:
import time
from tqdm import tqdm

results = []
start_time = time.time() - 30

for idx, text in enumerate(tqdm(df_table_name["cleaning4"], desc="Processing rows")):
    retry_count = 0

    if idx == 0:
        time.sleep(30)

    while True:
        try:
            if (idx) % 60 == 0:
                elapsed = int(time.time() - start_time + 1)
                wait_time = idx - elapsed + 1
                # print(f"idx {idx}, gap {elapsed}, start {start_time}, now {time.time()}")
                if wait_time > 0:
                    time.sleep(wait_time + 1)
                else:
                    pass
            result = execute_clovastudio(text, PROMPT_TEMPLATE_1)
            break  # 성공 시 루프 탈출
        except Exception as e:            
            retry_count += 1
            elapsed = int(time.time() - start_time + 1)
            wait_time = idx - elapsed + 1
            if wait_time > 0:
                time.sleep(wait_time + 1)
            if e == 429 :
                print(f"Error at index {idx}: {e}- Waiting {wait_time} seconds before retrying... (attempt {retry_count})")


    results.append(result)



df_table_name["구분"] = results

Processing rows: 100%|██████████| 11816/11816 [3:18:13<00:00,  1.01s/it]

In [175]:
import time
from tqdm import tqdm

results = []
start_time = time.time() - 30

for idx, text in enumerate(tqdm(df_table_name["cleaning4"], desc="Processing rows")):
    retry_count = 0

    if idx == 0:
        time.sleep(30)

    while True:
        try:
            if (idx) % 60 == 0:
                elapsed = int(time.time() - start_time + 1)
                wait_time = idx - elapsed + 1
                # print(f"idx {idx}, gap {elapsed}, start {start_time}, now {time.time()}")
                if wait_time > 0:
                    time.sleep(wait_time + 1)
                else:
                    pass
            result = execute_clovastudio(text, PROMPT_TEMPLATE_2)
            break  # 성공 시 루프 탈출
        except Exception as e:            
            retry_count += 1
            elapsed = int(time.time() - start_time + 1)
            wait_time = idx - elapsed + 1
            if wait_time > 0:
                time.sleep(wait_time + 1)
            if e == 429 :
                print(f"Error at index {idx}: {e}- Waiting {wait_time} seconds before retrying... (attempt {retry_count})")


    results.append(result)



df_table_name["대상"] = results

Processing rows: 100%|██████████| 11816/11816 [3:20:17<00:00,  1.02s/it]

In [178]:
df_table_name

,통계표ID,통계표명,지역,cleaning1,cleaning2,연령대,cleaning3,cleaning4,구분,대상
0,DT_1SA100,"세종특별자치시 농가, 농가인구",세종,"농가, 농가인구","농가, 농가인구",,"농가, 농가인구","농가, 농가인구",기준없음,"농가, 농가인구"
1,DT_1SA101,경지규모별 농가수,,경지규모별 농가수,경지규모별 농가수,,경지규모별 농가수,경지규모별 농가수,경지규모별,농가수
2,DT_1SA1011,논면적규모별 농가수,,논면적규모별 농가수,논면적규모별 농가수,,논면적규모별 농가수,논면적규모별 농가수,논면적 규모별,농가수
3,DT_1SA1011_01,"농가수, 논면적",,"농가수, 논면적","농가수, 논면적",,"농가수, 논면적","농가수, 논면적",기준없음,"농가수, 논면적"
4,DT_1SA1013,밭면적규모별 농가수,,밭면적규모별 농가수,밭면적규모별 농가수,,밭면적규모별 농가수,밭면적규모별 농가수,밭면적규모별,농가수
...,...,...,...,...,...,...,...,...,...,...
11811,DT_1A02038,시도별 · 이동유형별 귀산촌인,,시도별 · 이동유형별 귀산촌인,시도별 · 이동유형별 귀산촌인,,시도별 · 이동유형별 귀산촌인,시도별 · 이동유형별 귀산촌인,"행정구역별, 이동유형별",귀산촌인
11812,DT_1A02039,시도별 · 성별 · 연령별 귀산촌가구주,,시도별 · 성별 · 연령별 귀산촌가구주,시도별 · 성별 · 연령별 귀산촌가구주,,시도별 · 성별 · 연령별 귀산촌가구주,시도별 · 성별 · 연령별 귀산촌가구주,"시도별, 성별, 연령별",귀산촌가구주
11813,DT_1A02040,시도별(시군별) · 가구원수별 귀산촌가구,,시도별(시군별) · 가구원수별 귀산촌가구,시도별(시군별) · 가구원수별 귀산촌가구,,시도별(시군별) · 가구원수별 귀산촌가구,시도별(시군별) · 가구원수별 귀산촌가구,"행정구역별, 가구원수별",귀산촌가구
11814,DT_1A02041,시도별(시군별) · 가구 구성형태별 귀산촌가구,,시도별(시군별) · 가구 구성형태별 귀산촌가구,시도별(시군별) · 가구 구성형태별 귀산촌가구,,시도별(시군별) · 가구 구성형태별 귀산촌가구,시도별(시군별) · 가구 구성형태별 귀산촌가구,"행정구역별, 가구 구성형태별",귀산촌가구
11815,DT_1A02042,시도별 · 전입사유별 귀산촌가구,,시도별 · 전입사유별 귀산촌가구,시도별 · 전입사유별 귀산촌가구,,시도별 · 전입사유별 귀산촌가구,시도별 · 전입사유별 귀산촌가구,"시도별, 전입사유별",귀산촌가구

In [177]:
df_table_name.to_csv("./nodes/table_total.csv", index=False, encoding="utf-8-sig")

In [ ]:
import pandas as pd
from gensim.models import KeyedVectors

# fastText 벡터 로딩 (압축된 경우 자동 해제됨)
fasttext_model = KeyedVectors.load_word2vec_format('cc.ko.300.vec.gz', binary=False)

In [ ]:
# df_table_name["대상"]에 쉼표로 나뉜 단어들이 있다고 가정
target_list = set()

for items in df_table_name["대상"].dropna():
    for word in items.split(","):
        target_list.add(word.strip())

target_list = list(target_list)

In [ ]:
from itertools import combinations

edges = []

for w1, w2 in combinations(target_list, 2):
    if w1 in fasttext_model.key_to_index and w2 in fasttext_model.key_to_index:
        similarity = fasttext_model.similarity(w1, w2)
        # 유사도 임계값 설정 (예: 0.7 이상만 관계 생성)
        if similarity >= 0.7:
            edges.append((w1, w2, round(similarity, 4)))

In [ ]:
edges_target = pd.DataFrame(edges, columns=["source", "target", "similarity"])
edges_target.to_csv("target_similarity.csv", index=False)